Using cache found in C:\Users\mhroh/.cache\torch\hub\facebookresearch_dinov2_main
C:\Users\mhroh/.cache\torch\hub\facebookresearch_dinov2_main\dinov2\layers\swiglu_ffn.py:51: UserWarning: xFormers is not available (SwiGLU)
  warnings.warn("xFormers is not available (SwiGLU)")
C:\Users\mhroh/.cache\torch\hub\facebookresearch_dinov2_main\dinov2\layers\attention.py:33: UserWarning: xFormers is not available (Attention)
  warnings.warn("xFormers is not available (Attention)")
C:\Users\mhroh/.cache\torch\hub\facebookresearch_dinov2_main\dinov2\layers\block.py:40: UserWarning: xFormers is not available (Block)
  warnings.warn("xFormers is not available (Block)")
Using cache found in C:\Users\mhroh/.cache\torch\hub\facebookresearch_dinov2_main
Total parameters: 116806593
C:\Users\mhroh\Depth_Anything\src\train.py:171: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler()
0it [00:00, ?it/s]
2
Traceback (most recent call last):
  File "C:\Users\mhroh\anaconda3\envs\dl_env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mhroh\anaconda3\envs\dl_env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\mhroh\Depth_Anything\src\train.py", line 286, in <module>
    main()
  File "C:\Users\mhroh\Depth_Anything\src\train.py", line 283, in main
    train_student()
  File "C:\Users\mhroh\Depth_Anything\src\train.py", line 181, in train_student
    for batch_idx, (inputs, targets) in tqdm(enumerate(dataloader_student)):
  File "C:\Users\mhroh\anaconda3\envs\dl_env\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\mhroh\anaconda3\envs\dl_env\lib\site-packages\torch\utils\data\dataloader.py", line 708, in __next__
    data = self._next_data()
  File "C:\Users\mhroh\anaconda3\envs\dl_env\lib\site-packages\torch\utils\data\dataloader.py", line 764, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\mhroh\anaconda3\envs\dl_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 55, in fetch
    return self.collate_fn(data)
  File "C:\Users\mhroh\Depth_Anything\src\data\load_data.py", line 158, in cutMix_collate_fn
    mask = mask.to(group_2_pred.device)
NameError: name 'group_2_pred' is not defined
Traceback (most recent call last):
  File "C:\Users\mhroh\anaconda3\envs\dl_env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mhroh\anaconda3\envs\dl_env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\mhroh\Depth_Anything\src\train.py", line 286, in <module>
    main()
  File "C:\Users\mhroh\Depth_Anything\src\train.py", line 283, in main
    train_student()
  File "C:\Users\mhroh\Depth_Anything\src\train.py", line 181, in train_student
    for batch_idx, (inputs, targets) in tqdm(enumerate(dataloader_student)):
  File "C:\Users\mhroh\anaconda3\envs\dl_env\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\mhroh\anaconda3\envs\dl_env\lib\site-packages\torch\utils\data\dataloader.py", line 708, in __next__
    data = self._next_data()
  File "C:\Users\mhroh\anaconda3\envs\dl_env\lib\site-packages\torch\utils\data\dataloader.py", line 764, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\mhroh\anaconda3\envs\dl_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 55, in fetch
    return self.collate_fn(data)
  File "C:\Users\mhroh\Depth_Anything\src\data\load_data.py", line 158, in cutMix_collate_fn
    mask = mask.to(group_2_pred.device)
NameError: name 'group_2_pred' is not defined
